### ISSUE TITLE
sensor.plex_recently_added_* changes between movies and TV

### ISSUE THREAD

**Issue by jayscovill** [custom-components/sensor.plex_recently_added#29]
**Describe the Bug**
I have configured two different sensors.yaml entries for the sensor.plex_recently_sensor for both the "shows" and "movies" sections.
 
Two sensors are created, sensor.plex_recently_added and sensor.plex_recently_added_2.

The problem is which sensor displays movies or shows keeps on changing.  For instance I'll configure the Upcoming Media Card to display sensor.plex_recently_added_2 and and for a while it'll display recently added TV shows in Plex.  But after a few days it switches to displaying recently added movies. 

If I change it to sensor.plex_recently_added to show TV shows after a few days that sensor will change to showing recently added movies.

**Does the default Home Assistant Plex component work for you?**
Yes

**Home Assistant Version**
.100.1

My config:

- platform: plex_recently_added
  token: !secret plex_token
  host: 192.168.12.10
  port: 32400
  section_types:
  -show
  img_dir: /custom_ui/upcoming-media-card/images/plex/

- platform: plex_recently_added
  token: !secret plex_token
  host: 192.168.12.10
  port: 32400
  section_types:
  -movie
  img_dir: /custom_ui/upcoming-media-card/images/plex/

**Comment by maykar** [comment]
Use the `name:` config option to give each sensor a unique name:

```yaml
- platform: plex_recently_added
  name: Recently Added TV
  token: !secret plex_token
  host: 192.168.12.10
  port: 32400
  section_types:
  -show
  img_dir: /custom_ui/upcoming-media-card/images/plex/

- platform: plex_recently_added
  name: Recently Added Movies
  token: !secret plex_token
  host: 192.168.12.10
  port: 32400
  section_types:
  -movie
  img_dir: /custom_ui/upcoming-media-card/images/plex/ 
```

Then you can use `sensor.recently_added_movies` and  `sensor.recently_added_tv` instead of `sensor.plex_recently_added` and `sensor.plex_recently_added_2` in Upcoming Media Card's settings.

https://github.com/custom-components/sensor.plex_recently_added#multiple-sensor-sample-for-configurationyaml
