### ISSUE TITLE
section_types movies shows "TV shows"

### ISSUE THREAD

**Issue by clundin** [custom-components/sensor.plex_recently_added#43]
I use section_types for movie but it shows TV shows. 

```
 - platform: plex_recently_added
   name: Recently Added Movies # will create sensor.recently_added_movies
   token: !secret plex_token
   host: !secret plex_host
   port: 32400
   section_types:
   - movie
```
