### ISSUE TITLE
No Metadata field for "XXX"

### ISSUE THREAD

**Issue by whatdaybob** [custom-components/sensor.plex_recently_added#50]
Hi, I can see this issue has been posted before but no information was provided so it ended up stale. 

I have a repeating message in my logs every few minutes.

```logtalk 
2020-11-10 00:18:42 WARNING (MainThread) [custom_components.plex_recently_added.sensor] No Metadata field for "Films"
2020-11-10 00:21:42 WARNING (MainThread) [custom_components.plex_recently_added.sensor] No Metadata field for "Films"
2020-11-10 00:24:42 WARNING (MainThread) [custom_components.plex_recently_added.sensor] No Metadata field for "Films"
2020-11-10 00:27:42 WARNING (MainThread) [custom_components.plex_recently_added.sensor] No Metadata field for "Films"
```

my configuration that is causing the issue is below

```yaml
#-------------------------------------------
# Plex Recently Added Custom Sensors - https://github.com/custom-components/sensor.plex_recently_added/
#-------------------------------------------

  - platform: plex_recently_added
    name: plex_recently_added_movies
    entity_namespace: server
    token: !secret plex_x_token
    host: !secret ipaddr_Comp_Shield
    port: !secret port_Comp_Shield
    download_images: false
    on_deck: false
    section_types:
      - movie
```

and using `http://SERVER:PORT/library/sections?X-Plex-Token=PLEXTOKEN` this is the library reporting no metadata (useless info removed). I am using plex's new scanner but this issue persisted prior to this.

```xml
<Directory allowSync="" art="" composite="" filters="" refreshing="" thumb="" key="" type="movie" title="Films" agent="" scanner="Plex Movie" language="" uuid="" updatedAt="" createdAt="" scannedAt="" content="" directory="" contentChangedAt="" hidden="">
<Location id="30" path=""/>
</Directory>
```

I have removed and recreated the Film library and also checked that I do not have other `movie` type libraries. 

Any help at all would be great, thanks!

**Comment by maykar** [comment]
Are you saying that your "Films" library reports no movies when it does include movies or are you saying that there is an extra empty library being reported by plex?

If it is that "Films" includes movies, but is not reporting them. Go to this URL and see if it is reporting movies:

`http://[SERVER]:[PORT]/library/sections/30/all?X-Plex-Token=[TOKEN]`

If it is an extra empty library, go to `Settings > Manage > Libraries` and delete it.

Edit: Sorry, just saw that you checked that you didn't have any other libraries. Though having an ID of 30 for a library is unusually high.

**Comment by maykar** [comment]
If it is that "Films" includes movies, but is not reporting them. Go to this URL and see if it is reporting movies:

`https://[SERVER]:[PORT]/library/sections/30/all?X-Plex-Token=[TOKEN]`

**Comment by maykar** [comment]
If it is an extra empty library, go to `Settings > Manage > Libraries` and delete it.

**Comment by maykar** [comment]
Also, I'm sure it's not related, but remove both on_deck and entity_namespace from your config. Fairly sure entity_namespace won't do anything for this component and on_deck's default value is false, so just don't include it. 

```
  - platform: plex_recently_added
    name: plex_recently_added_movies
    token: !secret plex_x_token
    host: !secret ipaddr_Comp_Shield
    port: !secret port_Comp_Shield
    download_images: false
    section_types:
      - movie
```
