### ISSUE TITLE
Platform not found

### ISSUE THREAD

**Issue by mbarnes106** [custom-components/sensor.plex_recently_added#58]
HA core-2021.6.5 running on pi.

my system will not restart as it finds an error in the config.

Platform error sensor.plex_recently_added - Integration ‘plex_recently_added’ not found.

I commented it out, deleted the custom component, readded the newest version, restarted, but still get the error.

Here is my code:

```
sensor:
  - platform: plex_recently_added
    token: xxx
    host: 192.168.1.124
    port: 32400
```

and the files I need are in config/custom_components/plex_recently_added

Not sure what to try next?
