### ISSUE TITLE
After the update from 0.4.1 to 0.4.2 the thumbnails of the media are no longer shown

### ISSUE THREAD

**Issue by XalaTheShepard** [custom-components/sensor.plex_recently_added#75]
Since version 0.4.2 the thumbnails of the media are no longer shown in the sensor. Reverting back to 0.4.1 the thumbnails are again visible. 
Could you please add the thumbnails to the sensors? 

Thanks in advance. 

Kind regards, 

Robin

**Comment by XalaTheShepard** [comment]
![Schermafbeelding 2024-05-22 150908](https://github.com/custom-components/sensor.plex_recently_added/assets/69390987/451a1ecd-72e5-4116-b43d-7fa288800a50)

Please find enclosed the image with the current situation in version 0.4.2 
Kind regards

**Comment by mkanet** [comment]
Hi Robin, thank you for reporting this issue.  I just made a change; and, updated the version to `0.4.3`.  Can you please give it a try when you're notified of update?  Let me know how it works after you update and reboot home assistant.

**Comment by XalaTheShepard** [comment]
Dear Mkanet, I have updated the integration, but the thumbnails are still not loaded.
In the logs I find no issue with Plex nor with Recently added.
I am wondering if there is an issue in my configuration of my Lovelace Dashboard.
Please find enclosed the screenshots.

Many thanks for looking into this issue.
Kind regards,
Robin
![Screenshot_20240523_075605_io homeassistant companion android](https://github.com/custom-components/sensor.plex_recently_added/assets/69390987/aaa76cdb-1d39-4c18-ac38-cdda2ca5a74f)
![Screenshot_20240523_075543_io homeassistant companion android](https://github.com/custom-components/sensor.plex_recently_added/assets/69390987/f4ceee56-decd-4c50-8cb5-2eed69517297)

**Comment by XalaTheShepard** [comment]
data:
  - title_default: $title
    line1_default: $episode
    line2_default: $release
    line3_default: $number - $rating - $runtime
    line4_default: $genres
    icon: mdi:eye-off
  - airdate: "2024-05-17T20:04:21Z"
    aired: "2024-03-20"
    release: $day, $date $time
    flag: true
    title: "Ghostbusters: Frozen Empire"
    episode: "Ghostbusters: Frozen Empire"
    number: ""
    runtime: 116
    studio: Ghost Corps
    genres: ""
    rating: ""
    summary: >-
      De familie Spengler keert terug naar waar het allemaal begon – de
      iconische brandweerkazerne van New York City – om samen te werken met de
      originele Ghostbusters, die een uiterst geheim onderzoekslaboratorium
      hebben ontwikkeld om de opsporende geesten naar een hoger niveau te
      tillen. Maar wanneer de ontdekking van een oud artefact een kwade kracht
      ontketent, moeten nieuwe en oude Ghostbusters hun krachten bundelen om hun
      huis te beschermen en de wereld te redden van een tweede ijstijd.
    poster: /plex_plex_recently_added?path=/library/metadata/61865/thumb/1715994852
    fanart: /plex_plex_recently_added?path=/library/metadata/61865/art/1715994852
    deep_link: >-

**Comment by XalaTheShepard** [comment]
Forgot the details of the sensor

**Comment by loryanstrant** [comment]
I've got this issue as well, although I don't have a comparison as I only just got it working yesterday.
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/51473494/2d1ec3fe-d6f8-47f3-a76e-4162872772f6)

**Comment by pbaart** [comment]
I got the same issue after updating to the latest version (0.4.3), but I also moved the config from a yaml file to the frontend. 
The issue for me was a Mixed content issue. My Home Assistant is accessed over SSL, but was trying to retrieve the images over a non-SSL connection that was why the images were blocked by the browser.

I had configured my plex server without SSL, because it wouldn't login with SSL enabled on port 32400. Even with Verify SSL turned off it wouldn't login.
After changing my plex to a valid https url it was working again.
Maybe this helps in solving the issue for some of you.

```
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $number - $rating - $runtime
  line4_default: $genres
  icon: mdi:eye-off
- airdate: '2024-05-23T06:42:58Z'
  aired: '2024-05-23'
  release: $day, $date $time
  flag: true
  title: 'Star Trek: Discovery'
  episode: Lagrange Point
  season_num: '5'
  episode_num: '9'
  number: S05E09
  runtime: 46
  studio: ''
  genres: ''
  rating: ''
  summary: >-
    After Moll and the Breen capture a mysterious structure that contains the
    Progenitors' power, Captain Burnham must lead a covert mission to retrieve
    it before the Breen figure out how to use it.
  poster: /plex_recently_added?path=/library/metadata/69045/thumb/1716446580
  fanart: /plex_recently_added?path=/library/metadata/43526/art/1716339551
  deep_link: >-
    https://plex.xxxxx.xxx:443/web/index.html#!/server/afb6c664a192e78f7400b2e96919a15c92e78db2/details?key=%2Flibrary%2Fmetadata%2F69045
```
