### ISSUE TITLE
[Feature Request] Allow separation of movies and television

### ISSUE THREAD

**Issue by maykar** [custom-components/sensor.plex_recently_added#8]
This will require an update to the card as well, but I'd like to add the ability to create separate cards from one component...one card for TV one for Movies. Current thought is to split the data attribute into movie and tv attributes and combine in card by default unless the cards config hides one or the other.

**Comment by tmcarr** [comment]
To be honest, by library entirely might be useful. 

I wonder how hard it would be to expose seperate sensors for each library dynamically.

**Comment by maykar** [comment]
Yeah, library is the way to go. When it grabs the section numbers we can just grab the "type" too (returns "movie" or "show").

**Comment by 4meuwil** [comment]
I would also love to have one instance for each library, and even an on deck.

**Comment by 4meuwil** [comment]
i made a copy of the .py file named plex2_recently_added.py and changed line 87 to "plex2_recently_added".  Then made a duplicate sensor in HA , one with movies and one with shows...

**Comment by 4meuwil** [comment]
Have not figured out a way to do on deck though, even though the address is there...just doesn't scrape correctly.

**Comment by patrik996** [comment]
Just give us the ability to name the sensors entity. Then you can just add two sensors like below.
Right now it gets a random sensor.plex_recently_added_2 name which can change on the next reboot.

```yaml
  - platform: plex_recently_added
    token: !secret plex_api_key
    host: !secret docker_host
    port: 32400
    ssl: false
    ssl_cert: false
    download_images: false
    max: 5
    section_types:
    - movie
  - platform: plex_recently_added
    token: !secret plex_api_key
    host: !secret docker_host
    port: 32400
    ssl: false
    ssl_cert: false
    download_images: false
    max: 5
    section_types:
    - show
```

Edit: I created a pull request with this feature. https://github.com/custom-components/sensor.plex_recently_added/pull/26
