### ISSUE TITLE
Plex items aren’t clickable

### ISSUE THREAD

**Issue by ThePolarCat** [custom-components/sensor.plex_recently_added#80]
I suppose the items showing from the Plex On Deck should be clickable, however nothing happens when tapping on any.

**The Error**
No error!

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?
Yes

**What data does the sensor display if any?**
Feel free to censor information pertaining to titles, networks, etc.

it shows the item On Deck, as expected.

**What displays when visiting the API URL from the troubleshooting guide?**

Blank page but no error

**Does the default Home Assistant Plex component work for you?**
This is important to know, helps rule out issues with your Plex installation.

show the same data but also not clickable, it seems it’s a bug as other people are reporting it.

**Home Assistant Version**

Core
2024.5.4
Frontend
20240501.1

**Additional Context**
I’m not sure if it’s problem with this component or the card.

**Comment by mkanet** [comment]
Hi,  ere you using the default Show/Movie sensors?  Can you show me in a screenshot which items are still clickable and which items are not?  If none of the items are clickable, you are most likely using the wrong repo/version.  You need to make sure you are using the below version of the plex recently added **0.4.6 integration or newer**:

![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/6af6d3ac-cdf2-4e7d-afaf-473c66ccdcd5)

and Upcoming Media card **version 0.5.5**

![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/02879b9d-ba63-4874-8e8f-012e85ad9c07)

Also, can you go to:  **Home Assistant's Developer Tools/STATES** and type the name of the sensor entity that has unclickable items, then copy and paste the entity name and the first 5 items in the respective attributes? Below is mine (make sure you hide your plex token. I renamed my token to xxxxxxxxxxxxxxxxxxxx below).

`sensor.plex_recently_added`  

```
data:
  - title_default: $title
    line1_default: $episode
    line2_default: $release
    line3_default: $number - $rating - $runtime
    line4_default: $genres
    icon: mdi:eye-off
  - airdate: "2024-06-03T02:26:18Z"
    aired: "2021-05-11"
    release: $day, $date $time
    flag: true
    title: The Chosen
    episode: The Perfect Opportunity
    season_num: "2"
    episode_num: "4"
    number: S02E04
    runtime: 58
    studio: ""
    genres: ""
    rating: ""
    summary: >-
      As Jesus and the disciples head to Jerusalem to celebrate the Feast of
      Tabernacles, a new enemy follows them, while a familiar enemy awaits.
    poster: /plex_recently_added?path=/library/metadata/10995/thumb/1714927464
    fanart: /plex_recently_added?path=/library/metadata/10995/art/1714927464
    deep_link: >-
      https://mediaplex.mydomain.com:443/web/index.html#!/server/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/details?key=%2Flibrary%2Fmetadata%2F11432
  - airdate: "2024-05-25T03:26:42Z"
    aired: "2010-07-08"
    release: $day, $date $time
    flag: true
    title: Despicable Me
    episode: Despicable Me
    number: ""
    runtime: 94
    studio: Illumination
    genres: ""
    rating: ""
    summary: >-
      Gru, a criminal mastermind, adopts three orphans as pawns to carry out the
      biggest heist in history. His life takes an unexpected turn when the
      little girls see the evildoer as their potential father.
    poster: /plex_recently_added?path=/library/metadata/11293/thumb/1716607663
    fanart: /plex_recently_added?path=/library/metadata/11293/art/1716607663
    deep_link: >-
      https://mediaplex.mydomain.com:443/web/index.html#!/server/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/details?key=%2Flibrary%2Fmetadata%2F11293
  - airdate: "2024-05-18T14:53:20Z"
    aired: "2024-05-08"
    release: $day, $date $time
    flag: true
    title: IF
    episode: IF
    number: ""
    runtime: 95
    studio: Paramount
    genres: ""
    rating: ""
    summary: >-
      A young girl who goes through a difficult experience begins to see
      everyone's imaginary friends who have been left behind as their real-life
      friends have grown up.
    poster: /plex_recently_added?path=/library/metadata/11234/thumb/1717756400
    fanart: /plex_recently_added?path=/library/metadata/11234/art/1717756400
    deep_link: >-
      https://mediaplex.mydomain.com:443/web/index.html#!/server/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/details?key=%2Flibrary%2Fmetadata%2F11234
  - airdate: "2024-05-16T06:34:08Z"
    aired: "2024-05-16"
    release: $day, $date $time
    flag: true
    title: "Star Trek: Discovery"
    episode: Labyrinths
    season_num: "5"
    episode_num: "8"
    number: S05E08
    runtime: 57
    studio: ""
    genres: ""
    rating: ""
    summary: >-
      When Captain Burnham is trapped within a “mindscape” designed to test her
      worthiness to retrieve the Progenitor's powerful technology, Book, Rayner,
      and the crew of the U.S.S. Discovery must hold off the Breen long enough
      for her to escape.
    poster: /plex_recently_added?path=/library/metadata/9878/thumb/1717491811
    fanart: /plex_recently_added?path=/library/metadata/9878/art/1717491811
    deep_link: >-
      https://mediaplex.mydomain.com:443/web/index.html#!/server/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/details?key=%2Flibrary%2Fmetadata%2F11199
  - airdate: "2024-05-10T01:34:11Z"
    aired: "2024-05-09"
    release: $day, $date $time
    flag: true
    title: Sugar (2024)
    episode: The Friends You Keep
    season_num: "1"
    episode_num: "7"
    number: S01E07
    runtime: 36
    studio: ""
    genres: ""
    rating: ""
    summary: >-
      Sugar's fears for the safety of his friends lead him to a clandestine
      gathering where he learns a dangerous secret—and the truth about Olivia.
    poster: /plex_recently_added?path=/library/metadata/10771/thumb/1716376098
    fanart: /plex_recently_added?path=/library/metadata/10771/art/1716376098
    deep_link: >-
      https://mediaplex.mydomain.com:443/web/index.html#!/server/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/details?key=%2Flibrary%2Fmetadata%2F11162
```
