### ISSUE TITLE
[Feature Request] Return only one most recently added item from any selected libraries

### ISSUE THREAD

**Issue by anarion80** [custom-components/sensor.plex_recently_added#81]
**Is your feature request related to a problem? Please describe.**
Please consider adding an option to return only one most recently added item from any selected libraries, and not at least 1 per library like it is now. In some scenarios/dashboards all we care about is that one latest item to be displayed.

**Describe the solution you'd like**
If some config option is selected, then for example return only this:

```
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $number - $rating - $runtime
  line4_default: $genres
  icon: mdi:eye-off
- airdate: '2024-07-05T19:38:34Z'
  aired: '2024-07-03'
  release: $day, $date $time
  flag: true
  title: 'XXX'
  episode: 'XXX'
  number: ''
  runtime: 117
  studio: XXX
  genres: ''
  rating: ''
  summary: >-
    XXX
  trailer: XXX
  poster: /plex_plex_recently_added?path=/library/metadata/119414/thumb/1720208314
  fanart: /plex_plex_recently_added?path=/library/metadata/119414/art/1720208314
  deep_link: >-
    XXX
```
without the next item for another library. Just the latest from ANY selected library.
