### ISSUE TITLE
Shows data for TV Shows but not Movies

### ISSUE THREAD

**Issue by rpitera** [custom-components/sensor.plex_recently_added#82]
**Describe the Bug**
Get data for TV Shows but no data for Movies

**The Error**
No error on HA even with debug turned on.  Actually shows as successful in retrieving data for every log entry. 

`2024-08-15 09:28:17.257 DEBUG (MainThread) [custom_components.plex_recently_added.coordinator] Finished fetching plex_recently_added data in 0.158 seconds (success: True)`

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Pointing URL at http://PLEXHOST:32400/library/recentlyAdded?X-Plex-Token=MYPLEXTOKEN, I can see both my TV Shows and Movies that have been recently added up to current. The library section types match those in my component config.

**What data does the sensor display if any?**
TV SHOWS:
```
friendly_name: Kaizen Plex Recently Added Show
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $number - $rating - $runtime
  line4_default: $genres
  icon: mdi:eye-off
- airdate: '2024-08-14T00:58:00Z'
  aired: '2024-08-07'
  release: $day, $date $time
  flag: true
  title: The Ark
  episode: The Other You
  season_num: '2'
  episode_num: '4'
  number: S02E04
  runtime: 43
  studio: ''
  genres: ''
  rating: ''
  summary: >-
    When two realities intertwine, two theories on what could and shouldn't have
    been are revealed.
  trailer: null
  poster: /kaizen_plex_recently_added?path=/library/metadata/4647/thumb/1722759051
  fanart: /kaizen_plex_recently_added?path=/library/metadata/4647/art/1722759051
  deep_link: >-
    http://192.168.1.128:32400/web/index.html#!/server/91a8de06fc2940bb9536feee37f99f24151cc098/details?key=%2Flibrary%2Fmetadata%2F4761
- airdate: '2024-08-12T12:27:58Z'
  aired: '2024-08-12'
  release: $day, $date $time
  flag: true
  title: Futurama
  episode: The Temp
  season_num: '9'
  episode_num: '3'
  number: S09E03
  runtime: 23
  studio: ''
  genres: ''
  rating: ''
  summary: A mysterious temp worker takes over Fry's job... as well as his entire life.
  trailer: https://www.youtube.com/watch?v=xkGtMGs-k3Q
  poster: /kaizen_plex_recently_added?path=/library/metadata/3688/thumb/1722759051
  fanart: /kaizen_plex_recently_added?path=/library/metadata/3688/art/1722759051
  deep_link: >-
    http://192.168.1.128:32400/web/index.html#!/server/91a8de06fc2940bb9536feee37f99f24151cc098/details?key=%2Flibrary%2Fmetadata%2F4745
```
MOVIES:
```
friendly_name: Kaizen Plex Recently Added Movie
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $number - $rating - $runtime
  line4_default: $genres
  icon: mdi:eye-off
```

**What displays when visiting the API URL from the troubleshooting guide?**

I see all the relevant XML from both my recently added TV Shows AND my recently added movies. The data is rather large for this post so I didn't include it in the post but it is attached as a zip file.

**Does the default Home Assistant Plex component work for you?**
Yes

**Home Assistant Version**
HA - 2024.8.1
Component version - 0.48

**Additional Context**
I have checked my component configs and verified that I have chosen the proper sections (movie, show) and proper library types (Movies, TV Shows). I deleted and re-added them and then reloaded the component but no change.
