### ISSUE TITLE
Sensor not showing?

### ISSUE THREAD

**Issue by Apok1** [custom-components/sensor.plex_recently_added#95]
I have:

Installed the Upcoming Media Card (inc files)
Restarted
Added Card, shows - but blank no error
Added the HACS integration for 'sensor.plex_recently_added'
Added the resource "/local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1" as JS
Added to my configuration.yaml (in HA Folder):

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - platform: ntfy
    name: Ntfy
    topic: homeassistant
    url: http://192.168.1.123:5050
    token: mytoken

input_boolean:
  toggle_state_livingroom:
    name: Toggle State Living Room
    initial: off

sensor:
  - platform: plex_recently_added
    token: mytoken
    host: http://192.168.1.123
    port: 32400
```

I also tried 

```
sensor:
  - platform: plex_recently_added
    token: mytoken
    host: 192.168.1.123
    port: 32400
```

This is the card code:

```
entity: sensor.plex_upcoming_media
type: custom:upcoming-media-card
```

Plex upcoming media is showing in HACS, but not in integrations or States.

I also copied all the files into the same folders under homeassistant\custom_components\plex_recently_added.

I then restarted a couple of times, i redownloaded the HACS, though it didn't replace the files i added manually

Can anyone suggest what I need to do next?  I cannot point to the plex upcoming sensor in the upcoming media card as it doesn;t exist?
